Remove unneeded prototype declaration for strdup().
strdup is already defined in `string.h`.  Since strdup may be a macro,
the additional declaration lead to the following error message under
Debian:

```
make[4]: Entering directory '/build/montage-5.0+dfsg/lib/src/coord'
gcc -g -O2 -fdebug-prefix-map=/build/montage-5.0+dfsg=. -fstack-protector-strong
In file included from /usr/include/string.h:630:0,
                 from ccalc.c:5:
ccalc.c:28:7: error: expected identifier or '(' before '__extension__'
 char *strdup(const char *s1);
       ^
<builtin>: recipe for target 'ccalc.o' failed
make[4]: *** [ccalc.o] Error 1
```